---
title: Savi
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author:
email: contact@savilabs.org
description: Build incredible learning experiences. Savi creates LaunchPad, an application
  for creating educational projects collaboratively, and offers services to help educators
  get the most out of their projects.
baseurl:
url: http://www.savilabs.org
permalink: ":title"
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
markdown: kramdown
twitter_url: https://twitter.com/launchpadmoxie
facebook_url: https://www.facebook.com/people/Launch-Pad/100009444452196
twitter:
  username: launchpadmoxie
logo: "/images/brandmark.png"
google_site_verification: SCsHiHG1HGcd2Os-730zhF9mhfMQbUCmHNE8aIQiSMc
