---
title: Savi Learning
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@savilearning.org
description: |
  Build incredible learning experiences. Savi is the creator of LaunchPad, a web application for creating educational projects collaboratively, and offers services like coaching, workshops, and courses to help educators get the most out of their projects.
baseurl: 
url: http://www.savilearning.org
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
markdown: kramdown
